### ISSUE TITLE
ari tcp connector object not resolving being vpn. manual dns necessary

### ISSUE THREAD

**Issue by hemantjp** [clue/php-ami-react#45]
Hi.
i have to connect to a vpn as asterisk 2.10 is behind it.
the promise to the connector does not resolve.
```
require '../vendor/autoload.php';
use React\Socket\ConnectionInterface;

$loop = React\EventLoop\Factory::create();
$connector = new React\Socket\Connector($loop);
//$dns = $dnsResolverFactory->createCached('10.10.30.21', $loop);

$connector
    ->connect('pbx-stg.**.com:5038')
    ->then(
        function (ConnectionInterface $conn)  {
            echo "Connection established\n";
        },
        function (Exception $exception) use ($loop){
            echo "Cannot connect to server: " . $exception->getMessage();
            $loop->stop();
        });

$loop->run();
```
there is a dns issue.
i have to hard code the dns.

```
$connector = new React\Socket\Connector($loop,array(
    'dns' => '10.10.30.21'
));
```

what am i doing wrong.
i am able to use the Ratchet Websocket library to make connection to ARI.
there the dns is automatically resolved.i read the source[https://github.com/ratchetphp/Pawl/blob/master/src/Connector.php] but was unable to understand how it is handled effectively.

any tips to resolve this would be wonderful 

Thank You.

**Comment by clue** [comment]
> there is a dns issue.
i have to hard code the dns.

Thanks for reporting! Are you seeing any errors here or what kind of "issue" are you facing? Does using your custom DNS server fix the problem?

Yes, this projects uses the react/socket component in order to create the underlying TCP/IP connection. I see you've reported the same problem upstream in https://github.com/reactphp/socket/issues/144, so I'd like to address this there :+1: 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
